version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ${DEV_ENV}.Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
      - /usr/src/.next
    ports:
      - 3000:3000